### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by giladfrid009** [serpent-linux/website#3]
in the website, the rss feed icon link in the menu doesn't  work.

**Comment by ikeycode** [comment]
Bit more info other than "doesn't work" ? Nothing happens when clicking it, 404, what?

Works here, perhaps clear any caches and forcibly reload the site? The CNAME and A records were updated last night.
both resolving to the same host.
![Screenshot from 2020-07-08 10-30-46](https://user-images.githubusercontent.com/53261402/86902662-2bfa2600-c106-11ea-83aa-fade429c5cc6.png)
